services:
  es:
    image: elastic/elasticsearch:8.13.4
    container_name: checkhouse_es-local
    ports:
      - '9200:9200'
    environment:
      - node.name=${ES_USERNAME}
      - discovery.type=single-node # single-node 로 만든다.
      - discovery.seed_hosts=es
      - ELASTIC_PASSWORD=${ES_PASSWORD}
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.http.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=basic
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt http://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    volumes:
      - checkhouse_es_volume-local:/usr/share/es/data
      - certs:/usr/share/elasticsearch/config/certs
    networks:
      -  checkhouse-network_local

  kibana:
    container_name: checkhouse_kibana-local
    image: elastic/kibana:8.13.4
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    ports:
      - '5601:5601'
    depends_on:
      - es
    networks:
      - checkhouse-network_local
    restart: on-failure

  mysql:
    image: 'mysql:latest'
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - 3306:3306
  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379


volumes:
  checkhouse-volume_local:
  checkhouse_es_volume-local:
  certs:

networks:
  checkhouse-network_local:

